apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: learning
data:
  postgres.conf: |
    include_if_exists '/var/lib/postgresql/data/postgresql.conf'
    shared_preload_libraries = 'pg_stat_statements'
    max_connections = 150
  password: password
