apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: learning
  type: ClusterIP
  clusterIP: "None"
  ports:
  - name: postgres
    protocol: TCP
    port: 5432
    targetPort: 5432
