apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: fuzzer
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: fuzzer
            image: us.gcr.io/haskell-learn/fuzzer
          restartPolicy: OnFailure
