apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: migrate
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: migrate
            image: us.gcr.io/haskell-learn/migrate
          restartPolicy: OnFailure
