apiVersion: v1
kind: Service
metadata:
  name: server
  labels:
    service: server
spec:
  ports:
  - port: 80
    targetPort: 9000
    protocol: TCP
  type: LoadBalancer
  selector:
    service: server
