apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: learning
  type: ClusterIP
  clusterIP: "None"
  ports:
  - name: postgres
    protocol: TCP
    port: 6379
    targetPort: 6379
